minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale                   : "en-US"
title                    : "Microsoft HK GPS"
title_separator          : "-"
subtitle                 : "Azure OpenAI Demo Center"
url                      : "https://mshk-gps-openai-demo.github.io/"
logo                     : "/assets/image/logo.png"

# Build settings
theme: minimal-mistakes-jekyll

atom_feed:
  hide: true